###create a todo
POST http://localhost:5000/todo
Content-Type: application/json

{
    "title": "Create and endpoint",
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
}